version: '3.8'

services:
  telegram-bot:
    build: .
    environment:
      - BOT_TOKEN=your-telegram-bot-token-here
      - API_URL_TEMPLATE=https://your-api-url.com/like?uid={uid}&server_name={region}
      - WEBHOOK_URL=https://your-bot-webhook-url.com/
      - PORT=5000
    ports:
      - "5000:5000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M